python_binary(
  source = 'action_server.py',
  dependencies = [
    '3rdparty/python:slackclient',
    '3rdparty/python:Flask',
    '3rdparty/python:requests',
    'src/python/com/illinoistriangle/lib'
  ]
)
